Repository commercelayer/commercelayer-js-auth, pull requests merged in 2024-03, with the labels that each got.

#55 fix: add provisioning auth documentation
  .markdownlint.json
  README.md
  package.json
  pnpm-lock.yaml
Labels: documentation

#57 Allow custom headers
  package.json
  packages/js-auth/specs/authentication.spec.ts
  packages/js-auth/src/index.ts
  packages/js-auth/src/provisioning.ts
  packages/js-auth/src/types/index.ts
  pnpm-lock.yaml
Labels: enhancement

#59 Remove backward-compatibility. remove export `default` and named export `authentication`
  README.md
  packages/js-auth/specs/authentication.spec.ts
  packages/js-auth/src/core.ts
  packages/js-auth/src/index.ts
Labels: enhancement, breaking-change

#60 v5.0.0
  lerna.json
  packages/js-auth/package.json
Labels: ignore-for-release

#61 Move to Pure ESM. It still bundle to `cjs` and `esm`.
  .eslintrc.json
  .github/release.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  examples/cjs/index.js
  examples/cjs/package.json
  examples/esm/index.html
  examples/esm/index.js
  examples/esm/package.json
  package.json
  packages/js-auth/.eslintrc.cjs
  packages/js-auth/package.json
  packages/js-auth/specs/authentication.spec.ts
  packages/js-auth/specs/provisioning.spec.ts
  packages/js-auth/src/core.ts
  packages/js-auth/src/index.ts
  packages/js-auth/src/provisioning.ts
  packages/js-auth/src/types/authorizationCode.ts
  packages/js-auth/src/types/clientCredentials.ts
  packages/js-auth/src/types/index.ts
  packages/js-auth/src/types/password.ts
  packages/js-auth/src/types/refreshToken.ts
  packages/js-auth/tsconfig.json
  packages/js-auth/tsconfig.prod.esm.json
  packages/js-auth/tsconfig.prod.json
  packages/js-auth/tsup.config.js
  packages/js-auth/vitest.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#63 v5.1.0
  lerna.json
  packages/js-auth/package.json
Labels: ignore-for-release

#62 Update the `content-type` for provisioning to `application/json`
  README.md
  images/auth-code-browser.jpg
  packages/js-auth/README.md
  packages/js-auth/specs/provisioning.spec.ts
  packages/js-auth/src/core.ts
  packages/js-auth/src/provisioning.ts
  packages/js-auth/src/utils/doRequest.ts
  packages/js-auth/tsup.config.js
Labels: enhancement

#64 v5.2.0
  lerna.json
  packages/js-auth/package.json
Labels: ignore-for-release

#65 Add missing provisioning types
  packages/js-auth/src/index.ts
  pnpm-lock.yaml
Labels: bug

#67 v5.2.1
  lerna.json
  packages/js-auth/package.json
Labels: ignore-for-release

#68 New auth endpoint
  examples/bun/bun.lockb
  examples/bun/index.ts
  examples/bun/package.json
  examples/cjs/index.js
  examples/cloudflare-workers/src/index.ts
  examples/deno/index.ts
  examples/esm/index.js
  packages/js-auth/.env.example
  packages/js-auth/README.md
  packages/js-auth/specs/core.spec.ts
  packages/js-auth/specs/provisioning.spec.ts
  packages/js-auth/specs/types/global.d.ts
  packages/js-auth/src/authenticate.ts
  packages/js-auth/src/core.ts
  packages/js-auth/src/index.ts
  packages/js-auth/src/provisioning.ts
  packages/js-auth/src/types/authorizationCode.ts
  packages/js-auth/src/types/base.ts
  packages/js-auth/src/types/clientCredentials.ts
  packages/js-auth/src/types/index.ts
  packages/js-auth/src/types/password.ts
  packages/js-auth/src/types/refreshToken.ts
  packages/js-auth/src/utils/camelCaseToSnakeCase.spec.ts
  packages/js-auth/src/utils/camelCaseToSnakeCase.ts
  packages/js-auth/src/utils/doRequest.ts
  packages/js-auth/src/utils/mapKeys.spec.ts
  packages/js-auth/src/utils/mapKeys.ts
  packages/js-auth/src/utils/snakeCaseToCamelCase.spec.ts
  packages/js-auth/src/utils/snakeCaseToCamelCase.ts
  packages/js-auth/src/utils/snakeToCamelCase.ts
  pnpm-lock.yaml
Labels: enhancement, breaking-change

#70 Add custom header types
  packages/js-auth/src/types/base.ts
Labels: documentation

#69 Add an helper to decode the JWT
  examples/bun/index.ts
  examples/esm/index.js
  packages/js-auth/README.md
  packages/js-auth/global.d.ts
  packages/js-auth/specs/provisioning.spec.ts
  packages/js-auth/src/authenticate.spec.ts
  packages/js-auth/src/index.ts
  packages/js-auth/src/jwtDecode.spec.ts
  packages/js-auth/src/jwtDecode.ts
Labels: enhancement

#71 Add support to JWT Bearer
  package.json
  packages/js-auth/README.md
  packages/js-auth/package.json
  packages/js-auth/src/index.ts
  packages/js-auth/src/jwtDecode.ts
  packages/js-auth/src/jwtEncode.spec.ts
  packages/js-auth/src/jwtEncode.ts
  packages/js-auth/src/types/index.ts
  packages/js-auth/src/types/jwtBearer.ts
  packages/js-auth/src/utils/base64.spec.ts
  packages/js-auth/src/utils/base64.ts
  pnpm-lock.yaml
Labels: enhancement

#72 Add `revoke` method
  packages/js-auth/README.md
  packages/js-auth/src/index.ts
  packages/js-auth/src/revoke.spec.ts
  packages/js-auth/src/revoke.ts
  packages/js-auth/src/types/base.ts
  packages/js-auth/src/types/index.ts
Labels: enhancement

#73 Add `exports.types` to the package.json
  packages/js-auth/package.json
Labels: documentation

#74 Update README
  packages/js-auth/README.md
Labels: documentation
